### ISSUE TITLE
Библиотека контролов не хочет запускаться в SSR

### ISSUE THREAD

**Issue by dilbarov** [skbkontur/retail-ui#2068]
при попытке использовать контролы в SSR возникает ошибка 
`ReferenceError: navigator is not defined
    at Object.<anonymous> (C:\PROJECT\ssr-nest.js\node_modules\@skbkontur\react-ui\cjs\lib\utils.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\PROJECT\ssr-nest.js\node_modules\@skbkontur\react-ui\cjs\lib\events\keyboard\identifiers.js:1:1022)
    at Module._compile (internal/modules/cjs/loader.js:778:30)`

**Comment by zhzz** [comment]
@dilbarov Какая у вас версия библиотеки и как срочно вам нужен фикс?

**Comment by dilbarov** [comment]
версия 2.3.1, хотим через 1- 1.5 месяца приступать к работе

**Comment by zhzz** [comment]
Окей, думаю к тому времени сможем сделать.

**Comment by dilbarov** [comment]
Спасибо, будем ждать

**Comment by zhzz** [comment]
Выкатили тестовую версию с поддержкой SSR: `@skbkontur/react-ui@0.0.0-d911b322a7`.
